version: '3.8'

services:
  iot-agent:
    build:
      context: ./Agente
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./Agente/src:/app/src
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge